USE digi5;
SET foreign_key_checks = 0;
TRUNCATE TABLE apis_address;
TRUNCATE TABLE apis_credit_card;
TRUNCATE TABLE cli_customer_documents;
TRUNCATE TABLE cli_customer_mails;
TRUNCATE TABLE cli_customer_phones;
TRUNCATE TABLE cli_customers;
TRUNCATE TABLE cli_order_credit_card_actives;
TRUNCATE TABLE cli_order_itens;
TRUNCATE TABLE cli_orders;
TRUNCATE TABLE for_product_type_police_order_itens;
TRUNCATE TABLE pay_gateway_events;
TRUNCATE TABLE pay_register_logs;
TRUNCATE TABLE pay_registers;
ALTER TABLE `cli_orders` AUTO_INCREMENT=19;